language: cpp
git:
  depth: 3

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^(?i:continuous-linux)$/
    - /^(?i:continuous-osx)$/

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: g++
      sudo: required
      cache:
        ccache: false
        timeout: 1000
        directories:
          - $HOME/workspace/deps-build
          - $HOME/workspace/deps-install
          - $HOME/workspace/kmymoney-build

      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:beineri/opt-qt-5.12.1-xenial"
            - sourceline: "ppa:kubuntu-ppa/backports"

          packages:
            - g++-6
            - gcc-6
            - cmake
            - ninja-build
            - libxml-parser-perl
            - libaio-dev
            - libxcb-keysyms1
            - libxcb-keysyms1-dev
            - libudev1
            - libudev-dev
            - gperf
            - qt512base
            - qt512webengine
            - qt512svg
            - qt512declarative
            - qt512script
            - qt512tools
            - qt512x11extras
            - qt512translations
            - shared-mime-info
            - libxml2-dev
            - libxslt1-dev
            - libkf5kcmutils-dev
            - libkf5activities-dev
            - libkf5itemmodels-dev
            - libkf5itemviews-dev
            - extra-cmake-modules
            - libgpgme11-dev
            - libkf5notifications-dev
            - libkf5wallet-dev
            - kio-dev
            - libkf5archive-dev
            - libkf5kiowidgets5
            - libkf5kiofilewidgets5
            - libkio5
            - libkf5kiocore5
            - libkf5kiogui5

      before_install:
        - source /opt/qt512/bin/qt512-env.sh
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 10
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 10

      install:
        #- rm -fr $HOME/workspace/deps-build
        #- rm -fr $HOME/workspace/deps
        - export RUNTIME_TIMEOUT=0 #0 for hot cache, 2100 for cold cache
        - timeout ${RUNTIME_TIMEOUT} $TRAVIS_BUILD_DIR/packaging/linux/appimage/build.sh deps $HOME/workspace $TRAVIS_BUILD_DIR || true

      script:
        - |
          if (( ${RUNTIME_TIMEOUT} == 0 )); then
            $TRAVIS_BUILD_DIR/packaging/linux/appimage/build.sh kmymoney $HOME/workspace $TRAVIS_BUILD_DIR
            $TRAVIS_BUILD_DIR/packaging/linux/appimage/build.sh image $HOME/workspace $TRAVIS_BUILD_DIR
          else
            echo "Skipping script phase because warming cache only."
          fi

      before_cache:
        - rm -fr $HOME/workspace/deps-build/ext_boost/ext_boost-prefix/src/

      after_success:
        - |
          if (( ${RUNTIME_TIMEOUT} == 0 )); then
            #cd $HOME/workspace/kmymoney-build
            #ctest -V
            ls -lh $HOME/workspace/*
            cd $HOME/workspace/downloads
            wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
            export UPLOADTOOL_SUFFIX="linux"
            bash upload.sh $HOME/workspace/image-build/*.AppImage*
          else
            echo "Skipping after_success phase because warming cache only."
          fi

    - os: osx
      osx_image: xcode9.4
      compiler: clang
      sudo: required
      cache:
        timeout: 1000
        directories:
          - $HOME/Library/Caches/Homebrew
          - $HOME/workspace/deps-build
          - $HOME/workspace/deps-install
          - $HOME/workspace/kmymoney-build

      before_install:
        - brew update

      install:
        - brew install node@8
        - brew install qt
        - brew install meson
        - brew install ninja
        - brew install icu4c
        - brew install bison
        - export RUNTIME_TIMEOUT=2000 #0 for hot cache, 2100 for cold cache
        - gtimeout ${RUNTIME_TIMEOUT} $TRAVIS_BUILD_DIR/packaging/osx/dmgimage/build.sh deps $HOME/workspace $TRAVIS_BUILD_DIR || true

      script:
        - |
          if (( ${RUNTIME_TIMEOUT} == 0 )); then
            $TRAVIS_BUILD_DIR/packaging/osx/dmgimage/build.sh kmymoney $HOME/workspace $TRAVIS_BUILD_DIR
            $TRAVIS_BUILD_DIR/packaging/osx/dmgimage/build.sh image $HOME/workspace $TRAVIS_BUILD_DIR
          else
            echo "Skipping after_success phase because warming cache only."
          fi

      before_cache:
        - rm -fr $HOME/workspace/deps-build/ext_boost/ext_boost-prefix/src/
        #- brew cleanup

      after_success:
        - |
          if (( ${RUNTIME_TIMEOUT} == 0 )); then
            cd $HOME/workspace/downloads
            wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
            export UPLOADTOOL_SUFFIX="osx"
            bash upload.sh $HOME/workspace/image-build/*.dmg*
          else
            echo "Skipping after_success phase because warming cache only."
          fi
