language: cpp
git:
  depth: 3

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^(?i:continuous-linux)$/
    - /^(?i:continuous-osx)$/

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: g++
      sudo: required
      cache:
        ccache: false
        timeout: 1000
        directories:
          - $HOME/workspace/deps-build
          - $HOME/workspace/deps-install
          - $HOME/workspace/kmymoney-build

      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            #- sourceline: "ppa:beineri/opt-qt-5.12.1-xenial"
            #- sourceline: "ppa:kubuntu-ppa/backports"

          packages:
            - g++-6
            - gcc-6
            - cmake
            - ninja-build
            - libxml-parser-perl
            - libfam-dev
            - mesa-common-dev
            - libxfixes-dev
            - libxcb-xfixes0-dev
            - libaio-dev
            - libxcb-keysyms1-dev
            - libudev-dev
            - gperf
            - libgl1-mesa-dev
            #- qt512base
            #- qt512webengine
            #- qt512svg
            #- qt512declarative
            #- qt512tools
            #- qt512x11extras

      before_install:
        #- source /opt/qt512/bin/qt512-env.sh
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 10
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 10

      install:
        - rm -fr $HOME/workspace/deps-build/ext_frameworks
        - rm -fr $HOME/workspace/kmymoney-build
        #- rm -fr $HOME/workspace/deps
        - export RUNTIME_TIMEOUT=2100 #0 for hot cache, 2100 for cold cache
        - timeout ${RUNTIME_TIMEOUT} $TRAVIS_BUILD_DIR/packaging/linux/appimage/build.sh deps $HOME/workspace $TRAVIS_BUILD_DIR || true

      script:
        - |
          if (( ${RUNTIME_TIMEOUT} == 0 )); then
            $TRAVIS_BUILD_DIR/packaging/linux/appimage/build.sh kmymoney $HOME/workspace $TRAVIS_BUILD_DIR
            $TRAVIS_BUILD_DIR/packaging/linux/appimage/build.sh image $HOME/workspace $TRAVIS_BUILD_DIR
          else
            echo "Skipping script phase because warming cache only."
          fi

      before_cache:
        - rm -fr $HOME/workspace/deps-build/ext_boost/ext_boost-prefix/src/

      after_success:
        - |
          if (( ${RUNTIME_TIMEOUT} == 0 )); then
            #cd $HOME/workspace/kmymoney-build
            #ctest -V
            ls -lh $HOME/workspace/*
            cd $HOME/workspace/downloads
            wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
            export UPLOADTOOL_SUFFIX="linux"
            bash upload.sh $HOME/workspace/image-build/*.AppImage*
          else
            echo "Skipping after_success phase because warming cache only."
          fi

    - os: osx
      osx_image: xcode9.4
      compiler: clang
      sudo: required
      cache:
        timeout: 1000
        directories:
          - $HOME/Library/Caches/Homebrew
          - $HOME/workspace/deps-build
          - $HOME/workspace/deps-install
          - $HOME/workspace/kmymoney-build

      before_install:
        - brew update > /dev/null

      install:
        - brew install meson ninja bison > /dev/null #qt
        - rm -fr $HOME/workspace/deps-build/ext_frameworks
        - rm -fr $HOME/workspace/kmymoney-build
        #- rm -fr $HOME/workspace/deps-build/ext_frameworks/ext_kservice-prefix
        #- rm -fr $HOME/workspace/deps-build/ext_frameworks/ext_extra_cmake_modules-prefix
        #- find $HOME/workspace/deps-build -type f -name CMakeCache.txt -exec rm -fr {} \;
        #- find $HOME/workspace/kmymoney-build -type f -name CMakeCache.txt -exec rm -fr {} \;
        #- find $HOME/workspace/deps-build -type f -empty -name *install -exec rm -fr {} \;
        - export RUNTIME_TIMEOUT=2100 #0 for hot cache, 2100 for cold cache
        - gtimeout ${RUNTIME_TIMEOUT} $TRAVIS_BUILD_DIR/packaging/osx/dmgimage/build.sh deps $HOME/workspace $TRAVIS_BUILD_DIR || true

      script:
        - |
          if (( ${RUNTIME_TIMEOUT} == 0 )); then
            $TRAVIS_BUILD_DIR/packaging/osx/dmgimage/build.sh kmymoney $HOME/workspace $TRAVIS_BUILD_DIR
            $TRAVIS_BUILD_DIR/packaging/osx/dmgimage/build.sh image $HOME/workspace $TRAVIS_BUILD_DIR
          else
            echo "Skipping after_success phase because warming cache only."
          fi

      before_cache:
        - rm -fr $HOME/workspace/deps-build/ext_boost/ext_boost-prefix/src/
        #- brew cleanup

      after_success:
        - |
          if (( ${RUNTIME_TIMEOUT} == 0 )); then
            cd $HOME/workspace/downloads
            wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
            export UPLOADTOOL_SUFFIX="osx"
            bash upload.sh $HOME/workspace/image-build/*.dmg*
          else
            echo "Skipping after_success phase because warming cache only."
          fi
