language: cpp
git:
  depth: 3

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: g++
      sudo: required
      cache:
        ccache: true
        timeout: 1000
        directories:
          - $HOME/workspace

      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:beineri/opt-qt597-trusty"
          packages:
            - g++-6
            - gcc-6
            - cmake
            - ninja-build
            - libxml-parser-perl
            - libaio-dev
            - libxcb-keysyms1
            - libxcb-keysyms1-dev
            - libudev1
            - libudev-dev
            - gperf
            - qt59base
            - qt59webengine
            - qt59svg
            - qt59declarative
            - qt59script
            - qt59tools
            - qt59x11extras
            - qt59translations

      before_install:
        - source /opt/qt59/bin/qt59-env.sh
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 10
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 10

      install:
        - rm -fr $HOME/workspace/deps-build
        - rm -fr $HOME/workspace/deps
        - timeout 2100 $TRAVIS_BUILD_DIR/packaging/linux/appimage/build-deps.sh $HOME/workspace $TRAVIS_BUILD_DIR || true #0 for hot cache, 2100 for cold cache
        - touch NOTEST
        #- rm -fr NOTEST

      script:
        - |
          if [ ! -f NOTEST ]; then
            $TRAVIS_BUILD_DIR/packaging/linux/appimage/build-kmymoney.sh $HOME/workspace $TRAVIS_BUILD_DIR
            $TRAVIS_BUILD_DIR/packaging/linux/appimage/build-image.sh $HOME/workspace $TRAVIS_BUILD_DIR
          else
            echo "Skipping script phase because warming cache only."
          fi

      after_success:
        - |
          if [ ! -f NOTEST ]; then
            #cd $HOME/workspace/kmymoney-build
            #ctest -V
            ls -lh $HOME/workspace/*
            cd $TRAVIS_BUILD_DIR
            wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
            bash upload.sh $HOME/workspace/*.AppImage*
          else
            echo "Skipping after_success phase because warming cache only."
          fi

    - os: osx
      osx_image: xcode9.4
      compiler: clang
      sudo: required
      cache:
        timeout: 1000
        directories:
          - $HOME/Library/Caches/Homebrew
          - $HOME/workspace

      #before_cache:
        #- brew cleanup

      before_install:
        - brew update

      install:
        - brew install qt
        - brew install meson
        - brew install icu4c
        - brew install bison
        - export Qt5_DIR="/usr/local/opt/qt5/lib/cmake"
        - gtimeout 2100 $TRAVIS_BUILD_DIR/packaging/osx/dmgimage/build-deps.sh $HOME/workspace $TRAVIS_BUILD_DIR || true #0 for hot cache, 2100 for cold
        #- touch NOTEST
        - rm -fr NOTEST

      script:
        - |
          if [ ! -f NOTEST ]; then
            $TRAVIS_BUILD_DIR/packaging/osx/dmgimage/build-kmymoney.sh $HOME/workspace $TRAVIS_BUILD_DIR
          else
            echo "Skipping after_success phase because warming cache only."
          fi
