language: cpp
dist: trusty
compiler: g++
sudo: required
cache:
  ccache: true
  timeout: 1000
  directories:
    - $HOME/workspace

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: "ppa:beineri/opt-qt-5.10.1-trusty"
    packages:
      - g++-6
      - gcc-6
      - cmake
      - ninja-build
      - libxml-parser-perl
      - libaio-dev
      - libxcb-keysyms1
      - libxcb-keysyms1-dev
      - libudev1
      - libudev-dev
      - gperf
      - qt510base
      - qt510webengine
      - qt510svg
      - qt510declarative
      - qt510script
      - qt510tools
      - qt510x11extras

before_install:
  - source /opt/qt510/bin/qt510-env.sh
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 10
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 10

git:
  depth: 3

before_install:
  - export -f travis_fold

# cache-cold build (switch to this section if cache is not build up)
install:
  - timeout 2100 $TRAVIS_BUILD_DIR/packaging/linux/appimage/build-deps.sh $HOME/workspace $TRAVIS_BUILD_DIR || true
  - touch NOTEST

# cache-hot build
#install:
  #- $TRAVIS_BUILD_DIR/packaging/linux/appimage/build-deps.sh $HOME/workspace $TRAVIS_BUILD_DIR

script:
  - test -f NOTEST || $TRAVIS_BUILD_DIR/packaging/linux/appimage/build-kmymoney.sh $HOME/workspace $TRAVIS_BUILD_DIR

#after_success:
  #- cd $HOME/workspace/kmymoney-build
  #- ctest -V
