language: cpp
git:
  depth: 3

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: g++
      sudo: required
      cache:
        ccache: true
        timeout: 1000
        directories:
          - $HOME/workspace

      env:
        global:
          - MAKEFLAGS="-j 2"
          - RUNTIME_TIMEOUT=2100 #0 for hot cache, 2100 for cold cache

      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:beineri/opt-qt-5.10.1-trusty"
          packages:
            - g++-6
            - gcc-6
            - cmake
            - ninja-build
            - libxml-parser-perl
            - libaio-dev
            - libxcb-keysyms1
            - libxcb-keysyms1-dev
            - libudev1
            - libudev-dev
            - gperf
            - qt510base
            - qt510webengine
            - qt510svg
            - qt510declarative
            - qt510script
            - qt510tools
            - qt510x11extras

      before_install:
        - source /opt/qt510/bin/qt510-env.sh
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 10
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 10

      install:
        - timeout $RUNTIME_TIMEOUT $TRAVIS_BUILD_DIR/packaging/linux/appimage/build-deps.sh $HOME/workspace $TRAVIS_BUILD_DIR || true

      script:
        - echo "Nothing" || true
        #- if [ RUNTIME_TIMEOUT == 0 ]; then
            #$TRAVIS_BUILD_DIR/packaging/linux/appimage/build-kmymoney.sh $HOME/workspace $TRAVIS_BUILD_DIR;
            #$TRAVIS_BUILD_DIR/packaging/linux/appimage/build-image.sh $HOME/workspace $TRAVIS_BUILD_DIR;
          #else
            #echo "Skipping script phase because warming cache only.";
          #fi

      after_success:
        - echo "Nothing" || true
        #- if [ RUNTIME_TIMEOUT == 0 ]; then
            #cd $HOME/workspace/kmymoney-build;
            #ctest -V;
            #ls -lh $HOME/workspace/*;
            #cd $TRAVIS_BUILD_DIR;
            #wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh;
            #bash upload.sh $HOME/workspace/*.AppImage*;
          #else
            #echo "Skipping after_success phase because warming cache only.";
          #fi

    - os: osx
      osx_image: xcode9.4
      compiler: clang
      sudo: required
      cache:
        timeout: 1000
        directories:
          - $HOME/Library/Caches/Homebrew

      env:
        - RUNTIME_TIMEOUT_OSX=2100 #0 for hot cache, 2100 for cold cache

      before_cache:
        - brew cleanup

      before_install:
        - brew update
        - brew tap kde-mac/kde
        - "$(brew --repo)/Library/Taps/kde-mac/homebrew-kde/tools/all-fixes.sh"

      install:
        - brew install coreutils # for gtimeout functionality
        - gtimeout $RUNTIME_TIMEOUT $TRAVIS_BUILD_DIR/packaging/osx/dmgimage/build-deps.sh || true

      script:
        - echo "Nothing" || true
        #- if [ RUNTIME_TIMEOUT == 0 ]; then
            #echo "Something.";
          #else
            #echo "Skipping after_success phase because warming cache only.";
          #fi
