language: cpp
git:
  depth: 3

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: g++
      sudo: required
      cache:
        ccache: false
        timeout: 1000
        directories:
          - $HOME/workspace/deps-build
          - $HOME/workspace/kmymoney-build

      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:beineri/opt-qt597-trusty"
          packages:
            - g++-6
            - gcc-6
            - cmake
            - ninja-build
            - libxml-parser-perl
            - libaio-dev
            - libxcb-keysyms1
            - libxcb-keysyms1-dev
            - libudev1
            - libudev-dev
            - gperf
            - qt59base
            - qt59webengine
            - qt59svg
            - qt59declarative
            - qt59script
            - qt59tools
            - qt59x11extras
            - qt59translations

      before_install:
        - source /opt/qt59/bin/qt59-env.sh
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 10
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 10

      install:
        #- rm -fr $HOME/workspace/deps-build
        #- rm -fr $HOME/workspace/deps
        - export RUNTIME_TIMEOUT=0 #0 for hot cache, 2100 for cold cache
        - timeout ${RUNTIME_TIMEOUT} $TRAVIS_BUILD_DIR/packaging/linux/appimage/build-deps.sh $HOME/workspace $TRAVIS_BUILD_DIR || true

      script:
        - |
          if (( ${RUNTIME_TIMEOUT} == 0 )); then
            $TRAVIS_BUILD_DIR/packaging/linux/appimage/build-kmymoney.sh $HOME/workspace $TRAVIS_BUILD_DIR
            $TRAVIS_BUILD_DIR/packaging/linux/appimage/build-image.sh $HOME/workspace $TRAVIS_BUILD_DIR
          else
            echo "Skipping script phase because warming cache only."
          fi

      before_cache:
        # deletes install timestamps to force reinstalling dependencies into deps directory
        - find $HOME/workspace/deps-build -type f -name ext_*install -empty -exec rm -v {} \;
        - rm -fr $HOME/workspace/deps-build/ext_boost/ext_boost-prefix/src/
        - rm -fr $HOME/workspace/deps-build/ext_boost-prefix/src/ext_boost-stamp/ext_boost-mkdir
        - rm -fr $HOME/workspace/deps-build/ext_boost-prefix/src/ext_boost-stamp/ext_boost-download

      after_success:
        - |
          if (( ${RUNTIME_TIMEOUT} == 0 )); then
            #cd $HOME/workspace/kmymoney-build
            #ctest -V
            ls -lh $HOME/workspace/*
            cd $TRAVIS_BUILD_DIR
            wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
            bash upload.sh $HOME/workspace/*.AppImage*
          else
            echo "Skipping after_success phase because warming cache only."
          fi

    - os: osx
      osx_image: xcode9.4
      compiler: clang
      sudo: required
      cache:
        timeout: 1000
        directories:
          - $HOME/Library/Caches/Homebrew
          - $HOME/workspace/deps
          - $HOME/workspace/deps-build
          - $HOME/workspace/kmymoney-build

      before_install:
        - brew update

      install:
        - brew install node@8
        - brew install qt
        - brew install meson
        - brew install icu4c
        - brew install bison
        - export Qt5_DIR="/usr/local/opt/qt5/lib/cmake"
        - export RUNTIME_TIMEOUT=0 #0 for hot cache, 2100 for cold cache
        - gtimeout ${RUNTIME_TIMEOUT} $TRAVIS_BUILD_DIR/packaging/osx/dmgimage/build-deps.sh $HOME/workspace $TRAVIS_BUILD_DIR || true

      script:
        - |
          if (( ${RUNTIME_TIMEOUT} == 0 )); then
            export Qt5_DIR="/usr/local/opt/qt5/lib/cmake"
            export PATH=/usr/local/opt/qt5/bin:$PATH
            $TRAVIS_BUILD_DIR/packaging/osx/dmgimage/build-kmymoney.sh $HOME/workspace $TRAVIS_BUILD_DIR
            $TRAVIS_BUILD_DIR/packaging/osx/dmgimage/build-image.sh $HOME/workspace $TRAVIS_BUILD_DIR
          else
            echo "Skipping after_success phase because warming cache only."
          fi

      before_cache:
        #- find $HOME/workspace/deps-build -type f -name ext_*install -empty -exec rm -v {} \;
        - rm -fr $HOME/workspace/deps-build/ext_boost/ext_boost-prefix/src/
        #- rm -fr $HOME/workspace/deps-build/ext_boost-prefix/src/ext_boost-stamp/ext_boost-mkdir
        #- rm -fr $HOME/workspace/deps-build/ext_boost-prefix/src/ext_boost-stamp/ext_boost-download

        #- brew cleanup

      after_success:
        - |
          if (( ${RUNTIME_TIMEOUT} == 0 )) && false; then
            cd $TRAVIS_BUILD_DIR
            wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
            bash upload.sh $HOME/workspace/*.dmg*
          else
            echo "Skipping after_success phase because warming cache only."
          fi
