version: '{build}'

branches:
  only:
    - travis-builds

skip_tags: true
os: Visual Studio 2015

cache:
  - c:\deps-build
  - c:\deps-install

build: off

install:
  #- ps: Remove-Item "C:\deps-build\ext_frameworks\ext_breezeicons-prefix" -Force  -Recurse -ErrorAction SilentlyContinue
  #- ps: Remove-Item "C:\deps-build\ext_dbus" -Force  -Recurse -ErrorAction SilentlyContinue
  #- ps: Remove-Item "C:/deps-build/ext_kdewin" -Force  -Recurse -ErrorAction SilentlyContinue
  #- ps: Remove-Item "C:/deps-build/ext_qt" -Force  -Recurse -ErrorAction SilentlyContinue
  - cmd: powershell -ExecutionPolicy Bypass -File %APPVEYOR_BUILD_FOLDER%\packaging\windows\exe\build-from-ci.ps1 55 "/c" "%APPVEYOR_BUILD_FOLDER%"
