version: '{build}'

branches:
  only:
    - appveyor-builds
    
os: Visual Studio 2015

cache:
  - c:\deps-build
  - c:\deps-install

install:
  - ps: Write-Host "Hello world"
  - cmd: powershell -ExecutionPolicy Bypass -File APPVEYOR_BUILD_FOLDER/packaging/windows/exe/lauchBuild2.ps1 pacman-deps
  #- cmd: powershell -ExecutionPolicy Bypass -File %APPVEYOR_BUILD_FOLDER%\packaging\windows\exe\lauchBuild2.ps1 deps 10
          