version: '{build}'

branches:
  only:
    - appveyor-builds
    
os: Visual Studio 2015

cache:
  - c:\deps-build
  - c:\deps-install

build: off

install:
  - ps: Write-Host "Hello world"
  #- ps: Remove-Item "C:/deps-build/ext_frameworks" -Force  -Recurse -ErrorAction SilentlyContinue
  - cmd: powershell -ExecutionPolicy Bypass -File %APPVEYOR_BUILD_FOLDER%\packaging\windows\exe\lauchBuild2.ps1 pacman-deps
  - cmd: powershell -ExecutionPolicy Bypass -File %APPVEYOR_BUILD_FOLDER%\packaging\windows\exe\lauchBuild2.ps1 deps 50
  - cmd: powershell -ExecutionPolicy Bypass -File %APPVEYOR_BUILD_FOLDER%\packaging\windows\exe\lauchBuild2.ps1 kmymoney 50
  - cmd: cinst -y --no-progress nsis
  - cmd: powershell -ExecutionPolicy Bypass -File %APPVEYOR_BUILD_FOLDER%\packaging\windows\exe\lauchBuild2.ps1 image 50
  - cmd: powershell -ExecutionPolicy Bypass -File %APPVEYOR_BUILD_FOLDER%\packaging\windows\exe\lauchBuild2.ps1 upload-image 50
          